$defs:
  api_config:
    description: APIConfig contains options relevant to connecting to the K8s API
    type: object
    properties:
      auth_type:
        description: How to authenticate to the K8s API server.  This can be one of `none` (for no auth), `serviceAccount` (to use the standard service account token provided to the agent pod), or `kubeConfig` to use credentials from `~/.kube/config`.
        $ref: auth_type
      context:
        description: When using auth_type `kubeConfig`, override the current context.
        type: string
      kube_api_burst:
        description: KubeAPIBurst is the maximum burst of requests to the Kubernetes API. Uses client-go's default (10) if unset. Increase if you see client-side throttling warnings.
        type: integer
      kube_api_qps:
        description: KubeAPIQPS is the maximum number of queries per second to the Kubernetes API. Uses client-go's default (5) if unset. Increase if you see client-side throttling warnings.
        type: number
        x-customType: float32
  auth_type:
    description: AuthType describes the type of authentication to use for the K8s API
    type: string
