description: Config defines the configuration for the pprof receiver.
type: object
properties:
  remote:
    description: Configures pulling pprof profiles from a remote HTTP endpoint.
    type: object
    allOf:
      - $ref: go.opentelemetry.io/collector/scraper/scraperhelper.controller_config
      - $ref: go.opentelemetry.io/collector/config/confighttp.client_config
  file:
    description: Configures reading pprof profiles from files matching a glob pattern.
    type: object
    properties:
      include:
        description: Glob pattern for pprof files to scrape.
        type: string
    allOf:
      - $ref: go.opentelemetry.io/collector/scraper/scraperhelper.controller_config
  self:
    description: Configures profiling the running collector.
    type: object
    properties:
      block_profile_fraction:
        description: 'Fraction of blocking events that are profiled. A value <= 0 disables profiling. See https://golang.org/pkg/runtime/#SetBlockProfileRate for details.'
        type: integer
      mutex_profile_fraction:
        description: 'Fraction of mutex contention events that are profiled. A value <= 0 disables profiling. See https://golang.org/pkg/runtime/#SetMutexProfileFraction for details.'
        type: integer
    allOf:
      - $ref: go.opentelemetry.io/collector/scraper/scraperhelper.controller_config
  server:
    description: Configures an HTTP server that accepts pushed pprof profiles at POST /v1/pprof.
    type: object
    allOf:
      - $ref: go.opentelemetry.io/collector/config/confighttp.server_config
