type: object
properties:
  max_open_conn:
    description: The maximumn number of open connections to the sql server. <= 0 means unlimited
    type: integer
allOf:
  - $ref: /internal/sqlquery.config
