CREATE TABLE IF NOT EXISTS `%s`.`%s` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    resource_attributes JSON,
    resource_schema_url VARCHAR(512) NOT NULL DEFAULT '',
    scope_name VARCHAR(256) NOT NULL DEFAULT '',
    scope_version VARCHAR(64) NOT NULL DEFAULT '',
    scope_attributes JSON,
    scope_dropped_attr_count INT UNSIGNED NOT NULL DEFAULT 0,
    scope_schema_url VARCHAR(512) NOT NULL DEFAULT '',
    service_name VARCHAR(256) NOT NULL DEFAULT '',
    metric_name VARCHAR(256) NOT NULL DEFAULT '',
    metric_description TEXT,
    metric_unit VARCHAR(64) NOT NULL DEFAULT '',
    attributes JSON,
    start_time_unix DATETIME(6),
    time_unix DATETIME(6) NOT NULL,
    count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sum DOUBLE NOT NULL,
    quantile_values JSON,
    flags INT UNSIGNED NOT NULL DEFAULT 0,
    INDEX idx_time_unix (time_unix),
    INDEX idx_service_name (service_name),
    INDEX idx_metric_name (metric_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
