CREATE TABLE IF NOT EXISTS `%s`.`%s` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME(6) NOT NULL,
    trace_id VARCHAR(32) NOT NULL DEFAULT '',
    span_id VARCHAR(16) NOT NULL DEFAULT '',
    parent_span_id VARCHAR(16) NOT NULL DEFAULT '',
    trace_state VARCHAR(512) NOT NULL DEFAULT '',
    span_name VARCHAR(512) NOT NULL DEFAULT '',
    span_kind VARCHAR(32) NOT NULL DEFAULT '',
    service_name VARCHAR(256) NOT NULL DEFAULT '',
    resource_attributes JSON,
    scope_name VARCHAR(256) NOT NULL DEFAULT '',
    scope_version VARCHAR(64) NOT NULL DEFAULT '',
    span_attributes JSON,
    duration BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status_code VARCHAR(32) NOT NULL DEFAULT '',
    status_message TEXT,
    events JSON,
    links JSON,
    INDEX idx_timestamp (timestamp),
    INDEX idx_trace_id (trace_id),
    INDEX idx_service_name (service_name),
    INDEX idx_span_name (span_name(128)),
    INDEX idx_duration (duration)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
