// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("splunk_hec")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
)
