type: prometheus
display_name: Prometheus Exporter

status:
  class: exporter
  stability:
    beta: [metrics]
  distributions:
  - core
  - contrib
  codeowners:
    active: [Aneurysm9, dashpole, ArthurSens]

feature_gates:
  - id: exporter.prometheusexporter.DisableAddMetricSuffixes
    description: When enabled, the deprecated add_metric_suffixes configuration option is ignored and translation_strategy is always used
    stage: alpha
    from_version: "v0.132.0"
    reference_url: https://github.com/open-telemetry/opentelemetry-specification/pull/4533

tests:
  config:
    endpoint: "127.0.0.1:1234"
  goleak:
    ignore:
      top:
        # See https://github.com/census-instrumentation/opencensus-go/issues/1191 for more information.
        - "go.opencensus.io/stats/view.(*worker).start"