FROM docker.io/library/nginx:1.31@sha256:05b8cb60c354a44ab824ea6e7dc69b46d50762cdbe728a347a5b656e6fb3d7c4

COPY default.conf /etc/nginx/conf.d/default.conf
RUN \
    chown root:root /etc/nginx/conf.d/default.conf && \
    chmod 0644 /etc/nginx/conf.d/default.conf
