FROM docker.io/library/nginx:1.31@sha256:b34848eff6db786b6b1282d3a9c3fd0b5563dfb6d261df4923378b419e0d24f0

COPY default.conf /etc/nginx/conf.d/default.conf
RUN \
    chown root:root /etc/nginx/conf.d/default.conf && \
    chmod 0644 /etc/nginx/conf.d/default.conf
