self-hosted-runner:
  labels:
    - oracle-bare-metal-64cpu-1024gb-x86-64-ubuntu-24
    - cncf-ubuntu-8-32-x86
    - cncf-ubuntu-8-32-arm

config-variables: null

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # actionlint v1.7.12 doesn't support GitHub's '$/' self-repository syntax required by zizmor.
      # Remove once https://github.com/rhysd/actionlint/issues/711 is released.
      - 'specifying action "\$/.+" in invalid format because ref is missing'
