#!/bin/bash

modules=(
  "go.opentelemetry.io/collector/component"
  "go.opentelemetry.io/collector/confmap"
  "go.opentelemetry.io/collector/consumer"
  "go.opentelemetry.io/collector/exporter/loggingexporter"
  "go.opentelemetry.io/collector/exporter/otlpexporter"
  "go.opentelemetry.io/collector/exporter/otlphttpexporter"
  "go.opentelemetry.io/collector/extension/ballastextension"
  "go.opentelemetry.io/collector/extension/zpagesextension"
  "go.opentelemetry.io/collector/featuregate"
  "go.opentelemetry.io/collector/processor/batchprocessor"
  "go.opentelemetry.io/collector/processor/memorylimiterprocessor"
  "go.opentelemetry.io/collector/receiver/otlpreceiver"
  "go.opentelemetry.io/collector/semconv"
  "go.opentelemetry.io/collector/pdata"
)
