#!/bin/sh

# Updates MODULE inside go.mod if it is already present to version VERSION.

set -e

if grep -q "$MODULE " go.mod; then
  go get "$MODULE"@"$VERSION"
fi

# If MODULE is "go.opentelemetry.io/collector" need to update "go.opentelemetry.io/collector/model" as well.
if [ "$MODULE" == "go.opentelemetry.io/collector" ]; then
  MODEL=$MODULE"/model"
  if grep -q "$MODEL " go.mod; then
    go get "$MODEL"@"$VERSION"
  fi
fi
