#!/bin/sh

# Updates MODULE inside go.mod if it is already present to version VERSION.

set -e

if grep -q "$MODULE " go.mod; then
  go get "$MODULE"@"$VERSION"
fi

# If MODULE is "go.opentelemetry.io/collector" need to update "go.opentelemetry.io/collector/model"
# and "go.opentelemetry.io/collector/pdata" as well.
if [ "$MODULE" == "go.opentelemetry.io/collector" ]; then
  # TODO: Uncomment this after semconv releases.
  # SEMCONV=$MODULE"/semconv"
  # if grep -q "$SEMCONV " go.mod; then
  #   go get "$SEMCONV"@"$VERSION"
  # fi
  PDATA=$MODULE"/pdata"
  if grep -q "$PDATA " go.mod; then
    go get "$PDATA"@"$VERSION"
  fi
fi
