#!/bin/sh

# Updates MODULE inside go.mod if it is already present to version VERSION.

set -e

if grep -q "$MODULE " go.mod; then
  # If MODULE is "go.opentelemetry.io/collector" need to update "go.opentelemetry.io/collector/pdata" as well.
  if [ "$MODULE" == "go.opentelemetry.io/collector" ]; then
    MODEL=$MODULE"/model"
    go mod edit --dropreplace "$MODEL"
    go mod edit --replace "$MODEL"="$MODEL"@"$VERSION"
  fi
  go get "$MODULE"@"$VERSION"
fi
