package sqlserverreceiver

var waitTypes = []string{
	"Unknown",
	"CPU",
	"Worker Thread",
	"Lock",
	"Latch",
	"Buffer Latch",
	"Buffer IO",
	"Compilation",
	"SQL CLR",
	"Mirroring",
	"Transaction",
	"Idle",
	"Preemptive",
	"Service Broker",
	"Tran Log IO",
	"Network IO",
	"Parallelism",
	"Memory",
	"User Wait",
	"Tracing",
	"Full Text Search",
	"Other Disk IO",
	"Replication",
	"Log Rate Governor",
}

var detailedWaitTypes = map[string]uint{
	"Unknown":                           0,
	"SOS_SCHEDULER_YIELD":               1,
	"THREADPOOL":                        2,
	"RESOURCE_SEMAPHORE_QUERY_COMPILE":  7,
	"TRANSACTION_MUTEX":                 10,
	"LAZYWRITER_SLEEP":                  11,
	"SQLTRACE_BUFFER_FLUSH":             11,
	"SQLTRACE_INCREMENTAL_FLUSH_SLEEP":  11,
	"SQLTRACE_WAIT_ENTRIES":             11,
	"FT_IFTS_SCHEDULER_IDLE_WAIT":       11,
	"XE_DISPATCHER_WAIT":                11,
	"REQUEST_FOR_DEADLOCK_SEARCH":       11,
	"LOGMGR_QUEUE":                      11,
	"ONDEMAND_TASK_QUEUE":               11,
	"CHECKPOINT_QUEUE":                  11,
	"XE_TIMER_EVENT":                    11,
	"LOGMGR":                            14,
	"LOGBUFFER":                         14,
	"LOGMGR_RESERVE_APPEND":             14,
	"LOGMGR_FLUSH":                      14,
	"LOGMGR_PMM_LOG":                    14,
	"CHKPT":                             14,
	"WRITELOG":                          14,
	"ASYNC_NETWORK_IO":                  15,
	"NET_WAITFOR_PACKET":                15,
	"PROXY_NETWORK_IO":                  15,
	"EXTERNAL_SCRIPT_NETWORK_IOF":       15,
	"CXCONSUMER":                        16,
	"CXPACKET":                          16,
	"CXSYNC_CONSUMER":                   16,
	"CXSYNC_PORT":                       16,
	"EXCHANGE":                          16,
	"RESOURCE_SEMAPHORE":                17,
	"CMEMTHREAD":                        17,
	"CMEMPARTITIONED":                   17,
	"EE_PMOLOCK":                        17,
	"MEMORY_ALLOCATION_EXT":             17,
	"RESERVED_MEMORY_ALLOCATION_EXT":    17,
	"MEMORY_GRANT_UPDATE":               17,
	"WAITFOR":                           18,
	"WAIT_FOR_RESULTS":                  18,
	"BROKER_RECEIVE_WAITFOR":            18,
	"TRACEWRITE":                        19,
	"SQLTRACE_LOCK":                     19,
	"SQLTRACE_FILE_BUFFER":              19,
	"SQLTRACE_FILE_WRITE_IO_COMPLETION": 19,
	"SQLTRACE_FILE_READ_IO_COMPLETION":  19,
	"SQLTRACE_PENDING_BUFFER_WRITERS":   19,
	"SQLTRACE_SHUTDOWN":                 19,
	"QUERY_TRACEOUT":                    19,
	"TRACE_EVTNOTIFF":                   19,
	"FT_RESTART_CRAWL":                  20,
	"FULLTEXT GATHERER":                 20,
	"MSSEARCH":                          20,
	"FT_METADATA_MUTEX":                 20,
	"FT_IFTSHC_MUTEX":                   20,
	"FT_IFTSISM_MUTEX":                  20,
	"FT_IFTS_RWLOCK":                    20,
	"FT_COMPROWSET_RWLOCK":              20,
	"FT_MASTER_MERGE":                   20,
	"FT_PROPERTYLIST_CACHE":             20,
	"FT_MASTER_MERGE_COORDINATOR":       20,
	"PWAIT_RESOURCE_SEMAPHORE_FT_PARALLEL_QUERY_SYNC": 20,
	"ASYNC_IO_COMPLETION":                             21,
	"IO_COMPLETION":                                   21,
	"BACKUPIO":                                        21,
	"WRITE_COMPLETION":                                21,
	"IO_QUEUE_LIMIT":                                  21,
	"IO_RETRY":                                        21,
	"REPLICA_WRITES":                                  22,
	"FCB_REPLICA_WRITE":                               22,
	"FCB_REPLICA_READ":                                22,
	"PWAIT_HADRSIM":                                   22,
	"LOG_RATE_GOVERNOR":                               23,
	"POOL_LOG_RATE_GOVERNOR":                          23,
	"HADR_THROTTLE_LOG_RATE_GOVERNOR":                 23,
	"INSTANCE_LOG_RATE_GOVERNOR":                      23,
}
