// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					DnscheckDuration: DnscheckDurationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []DnscheckDurationMetricAttributeKey{DnscheckDurationMetricAttributeKeyDNSDomain, DnscheckDurationMetricAttributeKeyDNSRecordType, DnscheckDurationMetricAttributeKeyDNSServer},
					},
					DnscheckError: DnscheckErrorMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []DnscheckErrorMetricAttributeKey{DnscheckErrorMetricAttributeKeyDNSDomain, DnscheckErrorMetricAttributeKeyDNSRecordType, DnscheckErrorMetricAttributeKeyDNSServer, DnscheckErrorMetricAttributeKeyErrorMessage},
					},
					DnscheckStatus: DnscheckStatusMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []DnscheckStatusMetricAttributeKey{DnscheckStatusMetricAttributeKeyDNSDomain, DnscheckStatusMetricAttributeKeyDNSRcode, DnscheckStatusMetricAttributeKeyDNSRecordType, DnscheckStatusMetricAttributeKeyDNSResolvedAllIps, DnscheckStatusMetricAttributeKeyDNSResolvedIP, DnscheckStatusMetricAttributeKeyDNSServer},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					DnscheckDuration: DnscheckDurationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []DnscheckDurationMetricAttributeKey{DnscheckDurationMetricAttributeKeyDNSDomain, DnscheckDurationMetricAttributeKeyDNSRecordType, DnscheckDurationMetricAttributeKeyDNSServer},
					},
					DnscheckError: DnscheckErrorMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []DnscheckErrorMetricAttributeKey{DnscheckErrorMetricAttributeKeyDNSDomain, DnscheckErrorMetricAttributeKeyDNSRecordType, DnscheckErrorMetricAttributeKeyDNSServer, DnscheckErrorMetricAttributeKeyErrorMessage},
					},
					DnscheckStatus: DnscheckStatusMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []DnscheckStatusMetricAttributeKey{DnscheckStatusMetricAttributeKeyDNSDomain, DnscheckStatusMetricAttributeKeyDNSRcode, DnscheckStatusMetricAttributeKeyDNSRecordType, DnscheckStatusMetricAttributeKeyDNSResolvedAllIps, DnscheckStatusMetricAttributeKeyDNSResolvedIP, DnscheckStatusMetricAttributeKeyDNSServer},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(DnscheckDurationMetricConfig{}, DnscheckErrorMetricConfig{}, DnscheckStatusMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestDnscheckDurationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().DnscheckDuration
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []DnscheckDurationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric dnscheck.duration doesn't have an attribute invalid, valid attributes: [dns.domain, dns.record.type, dns.server]")

	cfg = DefaultMetricsConfig().DnscheckDuration
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestDnscheckErrorMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().DnscheckError
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []DnscheckErrorMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric dnscheck.error doesn't have an attribute invalid, valid attributes: [dns.domain, dns.record.type, dns.server, error.message]")

	cfg = DefaultMetricsConfig().DnscheckError
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestDnscheckStatusMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().DnscheckStatus
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []DnscheckStatusMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric dnscheck.status doesn't have an attribute invalid, valid attributes: [dns.domain, dns.rcode, dns.record.type, dns.resolved.all.ips, dns.resolved.ip, dns.server]")

	cfg = DefaultMetricsConfig().DnscheckStatus
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
