// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("datadogsemantics")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/datadogsemanticsprocessor"
)

const (
	TracesStability = component.StabilityLevelDeprecated
)
