$defs:
  attribute_error_type:
    description: AttributeErrorType specifies the value error.type attribute.
    type: integer
  attribute_network_io_direction:
    description: AttributeNetworkIoDirection specifies the value network.io.direction attribute.
    type: integer
  attribute_network_transport:
    description: AttributeNetworkTransport specifies the value network.transport attribute.
    type: integer
  attribute_nfs_server_repcache_status:
    description: AttributeNfsServerRepcacheStatus specifies the value nfs.server.repcache.status attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for nfs metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
  metrics_config:
    description: MetricsConfig provides config for nfs metrics.
    type: object
    properties:
      nfs.client.net.count:
        $ref: metric_config
      nfs.client.net.tcp.connection.accepted:
        $ref: metric_config
      nfs.client.operation.count:
        $ref: metric_config
      nfs.client.procedure.count:
        $ref: metric_config
      nfs.client.rpc.authrefresh.count:
        $ref: metric_config
      nfs.client.rpc.count:
        $ref: metric_config
      nfs.client.rpc.retransmit.count:
        $ref: metric_config
      nfs.server.fh.stale.count:
        $ref: metric_config
      nfs.server.io:
        $ref: metric_config
      nfs.server.net.count:
        $ref: metric_config
      nfs.server.net.tcp.connection.accepted:
        $ref: metric_config
      nfs.server.operation.count:
        $ref: metric_config
      nfs.server.procedure.count:
        $ref: metric_config
      nfs.server.repcache.requests:
        $ref: metric_config
      nfs.server.rpc.count:
        $ref: metric_config
      nfs.server.thread.count:
        $ref: metric_config
