$defs:
  attribute_network_io_direction:
    description: AttributeNetworkIoDirection specifies the value network.io.direction attribute.
    type: integer
  attribute_network_packet_type:
    description: AttributeNetworkPacketType specifies the value network.packet.type attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for interfaces metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
      resource_attributes:
        $ref: resource_attributes_config
  metrics_config:
    description: MetricsConfig provides config for interfaces metrics.
    type: object
    properties:
      system.network.errors:
        $ref: metric_config
      system.network.interface.status:
        $ref: metric_config
      system.network.io:
        $ref: metric_config
      system.network.packet.count:
        $ref: metric_config
      system.network.packet.dropped:
        $ref: metric_config
  resource_attribute_config:
    description: ResourceAttributeConfig provides common config for a particular resource attribute.
    type: object
    properties:
      enabled:
        type: boolean
      metrics_exclude:
        description: 'Experimental: MetricsExclude defines a list of filters for attribute values. If the list is not empty, metrics with matching resource attribute values will not be emitted. MetricsInclude has higher priority than MetricsExclude.'
        type: array
        items:
          $ref: go.opentelemetry.io/collector/filter.config
      metrics_include:
        description: 'Experimental: MetricsInclude defines a list of filters for attribute values. If the list is not empty, only metrics with matching resource attribute values will be emitted.'
        type: array
        items:
          $ref: go.opentelemetry.io/collector/filter.config
  resource_attributes_config:
    description: ResourceAttributesConfig provides config for interfaces resource attributes.
    type: object
    properties:
      host.ip:
        $ref: resource_attribute_config
      hw.type:
        $ref: resource_attribute_config
      os.name:
        $ref: resource_attribute_config
