// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"
	"slices"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string   `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []string `mapstructure:"attributes"`
	definedAttributes   []string
	requiredAttributes  []string
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	for _, val := range ms.EnabledAttributes {
		if !slices.Contains(ms.definedAttributes, val) {
			return fmt.Errorf("%v is not defined in metadata.yaml", val)
		}
	}

	for _, val := range ms.requiredAttributes {
		if !slices.Contains(ms.EnabledAttributes, val) {
			return fmt.Errorf("`attributes` field must contain required attribute: %v", val)
		}
	}

	if ms.AggregationStrategy != AggregationStrategySum &&
		ms.AggregationStrategy != AggregationStrategyAvg &&
		ms.AggregationStrategy != AggregationStrategyMin &&
		ms.AggregationStrategy != AggregationStrategyMax {
		return fmt.Errorf("invalid aggregation strategy set: '%v'", ms.AggregationStrategy)
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// AttributeConfig holds configuration information for a particular metric.
type AttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// MetricsConfig provides config for kafkametrics metrics.
type MetricsConfig struct {
	KafkaBrokerLogRetentionPeriod MetricConfig `mapstructure:"kafka.broker.log_retention_period"`
	KafkaBrokers                  MetricConfig `mapstructure:"kafka.brokers"`
	KafkaConsumerGroupLag         MetricConfig `mapstructure:"kafka.consumer_group.lag"`
	KafkaConsumerGroupLagSum      MetricConfig `mapstructure:"kafka.consumer_group.lag_sum"`
	KafkaConsumerGroupMembers     MetricConfig `mapstructure:"kafka.consumer_group.members"`
	KafkaConsumerGroupOffset      MetricConfig `mapstructure:"kafka.consumer_group.offset"`
	KafkaConsumerGroupOffsetSum   MetricConfig `mapstructure:"kafka.consumer_group.offset_sum"`
	KafkaPartitionCurrentOffset   MetricConfig `mapstructure:"kafka.partition.current_offset"`
	KafkaPartitionOldestOffset    MetricConfig `mapstructure:"kafka.partition.oldest_offset"`
	KafkaPartitionReplicas        MetricConfig `mapstructure:"kafka.partition.replicas"`
	KafkaPartitionReplicasInSync  MetricConfig `mapstructure:"kafka.partition.replicas_in_sync"`
	KafkaTopicLogRetentionPeriod  MetricConfig `mapstructure:"kafka.topic.log_retention_period"`
	KafkaTopicLogRetentionSize    MetricConfig `mapstructure:"kafka.topic.log_retention_size"`
	KafkaTopicMinInsyncReplicas   MetricConfig `mapstructure:"kafka.topic.min_insync_replicas"`
	KafkaTopicPartitions          MetricConfig `mapstructure:"kafka.topic.partitions"`
	KafkaTopicReplicationFactor   MetricConfig `mapstructure:"kafka.topic.replication_factor"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		KafkaBrokerLogRetentionPeriod: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"broker"},
			EnabledAttributes:   []string{"broker"},
		},
		KafkaBrokers: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{},
			EnabledAttributes:   []string{},
		},
		KafkaConsumerGroupLag: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"group", "topic", "partition"},
			EnabledAttributes:   []string{"group", "topic", "partition"},
		},
		KafkaConsumerGroupLagSum: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"group", "topic"},
			EnabledAttributes:   []string{"group", "topic"},
		},
		KafkaConsumerGroupMembers: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"group"},
			EnabledAttributes:   []string{"group"},
		},
		KafkaConsumerGroupOffset: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"group", "topic", "partition"},
			EnabledAttributes:   []string{"group", "topic", "partition"},
		},
		KafkaConsumerGroupOffsetSum: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"group", "topic"},
			EnabledAttributes:   []string{"group", "topic"},
		},
		KafkaPartitionCurrentOffset: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic", "partition"},
			EnabledAttributes:   []string{"topic", "partition"},
		},
		KafkaPartitionOldestOffset: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic", "partition"},
			EnabledAttributes:   []string{"topic", "partition"},
		},
		KafkaPartitionReplicas: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic", "partition"},
			EnabledAttributes:   []string{"topic", "partition"},
		},
		KafkaPartitionReplicasInSync: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic", "partition"},
			EnabledAttributes:   []string{"topic", "partition"},
		},
		KafkaTopicLogRetentionPeriod: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic"},
			EnabledAttributes:   []string{"topic"},
		},
		KafkaTopicLogRetentionSize: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic"},
			EnabledAttributes:   []string{"topic"},
		},
		KafkaTopicMinInsyncReplicas: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic"},
			EnabledAttributes:   []string{"topic"},
		},
		KafkaTopicPartitions: MetricConfig{
			Enabled: true,

			AggregationStrategy: AggregationStrategySum,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic"},
			EnabledAttributes:   []string{"topic"},
		},
		KafkaTopicReplicationFactor: MetricConfig{
			Enabled: false,

			AggregationStrategy: AggregationStrategyAvg,
			requiredAttributes:  []string{},
			definedAttributes:   []string{"topic"},
			EnabledAttributes:   []string{"topic"},
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for kafkametrics resource attributes.
type ResourceAttributesConfig struct {
	KafkaClusterAlias ResourceAttributeConfig `mapstructure:"kafka.cluster.alias"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		KafkaClusterAlias: ResourceAttributeConfig{
			Enabled: false,
		},
	}
}

// MetricsBuilderConfig is a configuration for kafkametrics metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
