// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/extension/tailstorage/pebbletailstorageextension")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/extension/tailstorage/pebbletailstorageextension")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                             metric.Meter
	mu                                                sync.Mutex
	registrations                                     []metric.Registration
	ExtensionPebbleTailStorageOperations              metric.Int64Counter
	ExtensionPebbleTailStorageReadErrorPartialReturns metric.Int64Counter
	ExtensionPebbleTailStorageReadErrorTraceDrops     metric.Int64Counter
	ExtensionPebbleTailStorageReadErrors              metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExtensionPebbleTailStorageOperations, err = builder.meter.Int64Counter(
		"otelcol_extension_pebble_tail_storage_operations",
		metric.WithDescription("Count of Pebble tail storage operations by operation and outcome [Development]"),
		metric.WithUnit("{operations}"),
	)
	errs = errors.Join(errs, err)
	builder.ExtensionPebbleTailStorageReadErrorPartialReturns, err = builder.meter.Int64Counter(
		"otelcol_extension_pebble_tail_storage_read_error_partial_returns",
		metric.WithDescription("Count of traces returned with partial data by Take because of a read-path error while on_read_error is return_partial [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ExtensionPebbleTailStorageReadErrorTraceDrops, err = builder.meter.Int64Counter(
		"otelcol_extension_pebble_tail_storage_read_error_trace_drops",
		metric.WithDescription("Count of traces dropped by Take because of a read-path error while on_read_error is drop_trace [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ExtensionPebbleTailStorageReadErrors, err = builder.meter.Int64Counter(
		"otelcol_extension_pebble_tail_storage_read_errors",
		metric.WithDescription("Count of Pebble tail storage read-path iterator creation, value read, payload decode, and iterator terminal errors [Development]"),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
