$defs:
  attribute_state:
    description: AttributeState specifies the value state attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      aggregation_strategy:
        type: string
      attributes:
        type: array
        items:
          type: string
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for cpu metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
  metrics_config:
    description: MetricsConfig provides config for cpu metrics.
    type: object
    properties:
      system.cpu.frequency:
        $ref: metric_config
      system.cpu.logical.count:
        $ref: metric_config
      system.cpu.physical.count:
        $ref: metric_config
      system.cpu.time:
        $ref: metric_config
      system.cpu.utilization:
        $ref: metric_config
