version: "3"
services:
  # Sample Go application producing counter metrics.
  prom-counter:
    container_name: prom-counter
    build:
      context: prom-counter
    restart: always
  # The Prometheus server:
  prometheus:
    image: prom/prometheus:v3.14.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # OpenTelemetry Collector
  otelcollector:
    image: otel/opentelemetry-collector-contrib-dev:latest@sha256:8c779b368c0c1b8f92e838550f6109218188664731b91e2837809b50e26ee58d
    container_name: otelcollector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - prometheus
