$defs:
  collection_role:
    type: string
description: Config defines configuration for aws ecs container metrics receiver.
type: object
properties:
  accelerated_compute_gpu_metrics_collection_interval:
    description: AcceleratedComputeGPUMetricsCollectionInterval is the interval at which gpu metrics should be collected. The default is 60 second.
    type: string
    format: duration
  accelerated_compute_metrics:
    description: EnableAcceleratedComputeMetrics enables features with accelerated compute resources where metrics are scraped from vendor specific sources
    type: boolean
  add_container_name_metric_label:
    description: The "ContainerName" attribute is the name of the container If false ContainerName label is not added The default value is false
    type: boolean
  add_full_pod_name_metric_label:
    description: The "FullPodName" attribute is the pod name including suffix If false FullPodName label is not added The default value is false
    type: boolean
  add_service_as_attribute:
    description: Whether to add the associated service name as attribute. The default is true
    type: boolean
  cluster_name:
    description: ClusterName can be used to explicitly provide the Cluster's Name for scenarios where it's not possible to auto-detect it using EC2 tags.
    type: string
  collection_interval:
    description: CollectionInterval is the interval at which metrics should be collected. The default is 60 second.
    type: string
    format: duration
  collection_role:
    description: CollectionRole defines the role of the collector hosting the receiver
    $ref: collection_role
  container_orchestrator:
    description: ContainerOrchestrator is the type of container orchestration service, e.g. eks or ecs. The default is eks.
    type: string
  enable_control_plane_metrics:
    description: EnableControlPlaneMetrics enables additional metrics sourced from the Kubernetes API server /metrics prometheus endpoint The default value is false.
    type: boolean
  host_ip:
    description: HostIP is an optional attribute to override the default host_ip in an EC2 environment
    type: string
  host_name:
    description: HostName is an optional attribute to override the default host_name in an EC2 environment
    type: string
  kube_config_path:
    description: KubeConfigPath is an optional attribute to override the default kube config path in an EC2 environment
    type: string
  leader_lock_name:
    description: LeaderLockName is an optional attribute to override the name of the locking resource (e.g. config map) used during the leader election process for EKS Container Insights. The elected leader is responsible for scraping cluster level metrics. The default value is "otel-container-insight-clusterleader".
    type: string
  leader_lock_using_config_map_only:
    description: LeaderLockUsingConfigMapOnly is an optional attribute to override the default behavior when obtaining a locking resource to be used during the leader election process for EKS Container Insights. By default, the leader election logic prefers a Lease and alternatively the combination of Lease & ConfigMap. When this flag is set to true, the leader election logic will be forced to use ConfigMap only. This flag mainly exists for backwards compatibility. The default value is false.
    type: boolean
  middleware:
    description: MiddlewareID is an ID for an extension that can be used to configure the AWS client.
    x-pointer: true
    type: string
    x-customType: go.opentelemetry.io/collector/component.ID
  prefer_full_pod_name:
    description: The "PodName" attribute is set based on the name of the relevant controllers like Daemonset, Job, ReplicaSet, ReplicationController, ... If it cannot be set that way and PrefFullPodName is true, the "PodName" attribute is set to the pod's own name. The default value is false
    type: boolean
  run_on_systemd:
    description: RunOnSystemd is an optional attribute to run the receiver in an EC2 environment
    type: boolean
allOf:
  - $ref: /internal/aws/awsutil.aws_session_settings
