extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  windows_perf_counters:
    collection_interval: 1s
    perfcounters:
      - object: "Memory"
        counters:
          - "Committed Bytes"
      - object: "Processor"
        instances: "*"
        counters:
          - "% Processor Time"
      - object: "Processor"
        instances: [1, 2]
        counters:
          - "% Idle Time"

exporters:
  debug:
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers: [windows_perf_counters]
      exporters: [prometheus, debug]

  extensions: [zpages]
