// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var K8sattrLabelsAnnotationsSingularAllowFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"k8sattr.labelsAnnotationsSingular.allow",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, default k8s label and annotation resource attribute keys will be singular, instead of plural"),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39774"),
	featuregate.WithRegisterFromVersion("v0.125.0"),
)
