// Copyright  OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dockerobserver

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	dtypes "github.com/docker/docker/api/types"
	"github.com/docker/go-connections/nat"
	"github.com/open-telemetry/opentelemetry-collector-contrib/extension/observer"
	"go.opentelemetry.io/collector/component"
	"go.uber.org/zap"
)

var _ (component.Extension) = (*dockerObserver)(nil)

type dockerObserver struct {
	logger *zap.Logger
	config *Config
}

func (d *dockerObserver) Start(ctx context.Context, host component.Host) error {
	return nil
}

func (d *dockerObserver) Shutdown(ctx context.Context) error {
	return nil
}

// endpointsForContainer generates a list of observer.Endpoint given a Docker ContainerJSON.
// This function will only generate endpoints if a container is in the Running state and not Paused.
func (d *dockerObserver) endpointsForContainer(c *dtypes.ContainerJSON) []observer.Endpoint {
	cEndpoints := make([]observer.Endpoint, 0)

	if c.State.Running && !c.State.Paused {
		knownPorts := map[nat.Port]bool{}
		for k := range c.Config.ExposedPorts {
			knownPorts[k] = true
		}

		// iterate over exposed ports and try to create endpoints
		for portObj := range knownPorts {
			endpoint := d.endpointForPort(portObj, c)
			// the endpoint was not set, so we'll drop it
			if endpoint == (observer.Endpoint{}) {
				continue
			}
			cEndpoints = append(cEndpoints, endpoint)
		}
	}

	for _, e := range cEndpoints {
		s, _ := json.MarshalIndent(e, "", "\t")
		d.logger.Debug(fmt.Sprintf("Discovered Docker container endpoint:\n%v\n", string(s)))
	}

	return cEndpoints
}

// endpointForPort creates an observer.Endpoint for a given port that is exposed in a Docker container.
// Each endpoint has a unique ID generated by the combination of the container.ID, container.Name,
// underlying host name, and the port number.
// Uses the user provided config settings to override certain fields.
func (d *dockerObserver) endpointForPort(portObj nat.Port, c *dtypes.ContainerJSON) observer.Endpoint {
	endpoint := observer.Endpoint{}
	port := portObj.Int()
	proto := portObj.Proto()

	mappedPort, mappedIP := findHostMappedPort(c, portObj)
	if d.config.IgnoreNonHostBindings && mappedPort == 0 && mappedIP == "" {
		return endpoint
	}

	// unique ID per host/container/port
	// (docker_observer)container_ID-container_name-host_name:port
	id := observer.EndpointID(
		fmt.Sprintf(
			"(%s)%s-%s-%s:%d",
			typeStr, c.ID, c.Name, mappedIP, mappedPort,
		),
	)

	details := &observer.Container{
		Name:        c.Name,
		Image:       c.Config.Image,
		Command:     strings.Join(c.Config.Cmd, " "),
		ContainerID: c.ID,
		Transport:   portProtoToTransport(proto),
		Labels:      c.Config.Labels,
	}
	var target string

	// Set our target and hostname based on config settings
	if d.config.UseHostnameIfPresent && c.Config.Hostname != "" {
		target = c.Config.Hostname
		details.Host = c.Config.Hostname
	} else {
		// Use the IP Address of the first network we iterate over.
		// This can be made configurable if so desired.
		for _, n := range c.NetworkSettings.Networks {
			target = n.IPAddress
			details.Host = n.IPAddress
			break
		}

		// If we still haven't gotten a host at this point and we are using
		// host bindings, just make it localhost.
		if target == "" && d.config.UseHostBindings {
			target = "127.0.0.1"
			details.Host = "127.0.0.1"
		}
	}

	// If we are using HostBindings & port and IP are set, use those
	if d.config.UseHostBindings && mappedPort != 0 && mappedIP != "" {
		details.Host = mappedIP
		target = mappedIP
		details.Port = uint16(mappedPort)
		details.AlternatePort = uint16(port)
		if details.Host == "0.0.0.0" {
			details.Host = "127.0.0.1"
			target = "127.0.0.1"
		}
	} else {
		details.Port = uint16(port)
		details.AlternatePort = uint16(mappedPort)
	}

	endpoint = observer.Endpoint{
		ID:      id,
		Target:  target,
		Details: details,
	}

	return endpoint
}

// FindHostMappedPort returns the port number of the docker port binding to the
// underlying host, or 0 if none exists.  It also returns the mapped ip that the
// port is bound to on the underlying host, or "" if none exists.
func findHostMappedPort(c *dtypes.ContainerJSON, exposedPort nat.Port) (int, string) {
	bindings := c.NetworkSettings.Ports[exposedPort]

	for _, binding := range bindings {
		if port, err := nat.ParsePort(binding.HostPort); err == nil {
			return port, binding.HostIP
		}
	}
	return 0, ""
}

// Valid proto for docker containers should be tcp, udp, sctp
// https://github.com/docker/go-connections/blob/v0.4.0/nat/nat.go#L116
func portProtoToTransport(proto string) observer.Transport {
	switch proto {
	case "tcp":
		return observer.ProtocolTCP
	case "udp":
		return observer.ProtocolUDP
	}
	return observer.ProtocolUnknown
}

// newObserver creates a new docker observer extension.
func newObserver(logger *zap.Logger, config *Config) (component.Extension, error) {
	return &dockerObserver{logger: logger, config: config}, nil
}
