FROM otelcol-sdnotify-base:latest

COPY extension/sdnotifyextension/testdata/otelcol-bad-exporter.yaml /etc/otelcol/config.yaml

COPY extension/sdnotifyextension/testdata/otelcol.service /etc/systemd/system/otelcol.service
RUN ln -s /etc/systemd/system/otelcol.service /etc/systemd/system/multi-user.target.wants/otelcol.service
