INSERT INTO "%s"."%s" (
    ResourceAttributes,
    ResourceAttributesKeys,
    ResourceSchemaUrl,
    ScopeName,
    ScopeVersion,
    ScopeAttributes,
    ScopeAttributesKeys,
    ScopeDroppedAttrCount,
    ScopeSchemaUrl,
    ServiceName,
    MetricName,
    MetricDescription,
    MetricUnit,
    Attributes,
    AttributesKeys,
    StartTimeUnix,
    TimeUnix,
    Count,
    Sum,
    ValueAtQuantiles.Quantile,
    ValueAtQuantiles.Value,
    Flags) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
