CREATE TABLE IF NOT EXISTS %q.%q %s (
    Timestamp DateTime64(9) CODEC(Delta, ZSTD(1)),
    ProfileId String CODEC(ZSTD(1)),
    SampleType LowCardinality(String) CODEC(ZSTD(1)),
    SampleUnit LowCardinality(String) CODEC(ZSTD(1)),
    ServiceName LowCardinality(String) CODEC(ZSTD(1)),
    ResourceAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    ScopeName String CODEC(ZSTD(1)),
    ScopeVersion String CODEC(ZSTD(1)),
    ProfileAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    SampleAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
    StackHash UInt64 CODEC(ZSTD(1)),
    Addresses Array(UInt64) CODEC(ZSTD(1)),
    FunctionNames Array(LowCardinality(String)) CODEC(ZSTD(1)),
    FileNames Array(LowCardinality(String)) CODEC(ZSTD(1)),
    LineNumbers Array(Int32) CODEC(ZSTD(1)),
    MappingFileNames Array(LowCardinality(String)) CODEC(ZSTD(1)),
    Values Array(Int64) CODEC(ZSTD(1)),
    TimestampsUnixNano Array(UInt64) CODEC(ZSTD(1)),
    DurationNano UInt64 CODEC(ZSTD(1)),
    Period Int64 CODEC(ZSTD(1)),
    PeriodType LowCardinality(String) CODEC(ZSTD(1)),
    PeriodUnit LowCardinality(String) CODEC(ZSTD(1)),
    TraceId String CODEC(ZSTD(1)),
    SpanId String CODEC(ZSTD(1)),
    `__otel_materialized_k8s.cluster.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.cluster.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.container.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.container.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.deployment.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.deployment.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.namespace.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.namespace.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.node.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.node.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.pod.name` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.pod.name'] CODEC(ZSTD(1)),
    `__otel_materialized_k8s.pod.uid` LowCardinality(String) MATERIALIZED ResourceAttributes['k8s.pod.uid'] CODEC(ZSTD(1)),
    `__otel_materialized_deployment.environment.name` LowCardinality(String) MATERIALIZED ResourceAttributes['deployment.environment.name'] CODEC(ZSTD(1)),
    `__otel_materialized_service.namespace` LowCardinality(String) MATERIALIZED ResourceAttributes['service.namespace'] CODEC(ZSTD(1)),
    `__otel_materialized_service.instance.id` LowCardinality(String) MATERIALIZED ResourceAttributes['service.instance.id'] CODEC(ZSTD(1)),
    INDEX idx_profile_id ProfileId TYPE text(tokenizer = 'array'),
    INDEX idx_trace_id TraceId TYPE text(tokenizer = 'array'),
    INDEX idx_res_attr_key mapKeys(ResourceAttributes) TYPE text(tokenizer = 'array'),
    INDEX idx_res_attr_value mapValues(ResourceAttributes) TYPE text(tokenizer = 'array'),
    INDEX idx_sample_attr_key mapKeys(SampleAttributes) TYPE text(tokenizer = 'array'),
    INDEX idx_sample_attr_value mapValues(SampleAttributes) TYPE text(tokenizer = 'array'),
    INDEX idx_function_names FunctionNames TYPE text(tokenizer = 'splitByNonAlpha')
) ENGINE = %s
PARTITION BY toDate(Timestamp)
ORDER BY (ServiceName, SampleType, toDateTime(Timestamp))
%s
SETTINGS index_granularity=8192, ttl_only_drop_parts = 1
