display_name: Prometheus Remote Write Receiver
type: prometheusremotewrite

description: |
  This receiver implements the
  [Prometheus Remote Write 2.0 protocol](https://prometheus.io/docs/specs/prw/remote_write_spec_2_0/).

status:
  class: receiver
  stability:
    alpha: [metrics]
  distributions: [contrib]
  codeowners:
    active: [dashpole, ArthurSens, perebaj]
tests:
  config:
  goleak:
    ignore:
      top:
        # See https://github.com/census-instrumentation/opencensus-go/issues/1191 for more information.
        - "go.opencensus.io/stats/view.(*worker).start"
