description: FileLogConfig defines configuration for the file_log receiver
type: object
allOf:
  - $ref: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.config
  - $ref: github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.base_config
