$defs:
  attribute_state:
    description: AttributeState specifies the value state attribute.
    type: integer
  attribute_system_memory_linux_hugepages_state:
    description: AttributeSystemMemoryLinuxHugepagesState specifies the value system.memory.linux.hugepages.state attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      aggregation_strategy:
        type: string
      attributes:
        type: array
        items:
          type: string
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for memory metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
  metrics_config:
    description: MetricsConfig provides config for memory metrics.
    type: object
    properties:
      system.linux.memory.available:
        $ref: metric_config
      system.linux.memory.dirty:
        $ref: metric_config
      system.memory.limit:
        $ref: metric_config
      system.memory.linux.hugepages.limit:
        $ref: metric_config
      system.memory.linux.hugepages.page_size:
        $ref: metric_config
      system.memory.linux.hugepages.reserved:
        $ref: metric_config
      system.memory.linux.hugepages.surplus:
        $ref: metric_config
      system.memory.linux.hugepages.usage:
        $ref: metric_config
      system.memory.linux.hugepages.utilization:
        $ref: metric_config
      system.memory.linux.shared:
        $ref: metric_config
      system.memory.page_size:
        $ref: metric_config
      system.memory.usage:
        $ref: metric_config
      system.memory.utilization:
        $ref: metric_config
