$defs:
  attribute_direction:
    description: AttributeDirection specifies the value direction attribute.
    type: integer
  attribute_protocol:
    description: AttributeProtocol specifies the value protocol attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      aggregation_strategy:
        type: string
      attributes:
        type: array
        items:
          type: string
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for network metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
  metrics_config:
    description: MetricsConfig provides config for network metrics.
    type: object
    properties:
      system.network.connections:
        $ref: metric_config
      system.network.conntrack.count:
        $ref: metric_config
      system.network.conntrack.max:
        $ref: metric_config
      system.network.dropped:
        $ref: metric_config
      system.network.errors:
        $ref: metric_config
      system.network.io:
        $ref: metric_config
      system.network.packets:
        $ref: metric_config
