// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("cfgarden_observer")
	ScopeName = "otelcol/cfgardenobserver"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
