// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/featuregate"
)

var PkgTranslatorZipkinDontEmitV0CloudResourceConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.DontEmitV0CloudResourceConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator no longer emits the deprecated faas.id attribute (semconv v1.18.0). Requires pkg.translator.zipkin.EmitV1CloudResourceConventions to also be enabled."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45080"),
	featuregate.WithRegisterFromVersion("v0.155.0"),
)

var PkgTranslatorZipkinDontEmitV0HTTPConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.DontEmitV0HttpConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator no longer emits the deprecated http.status_code attribute (semconv v1.25.0). Requires pkg.translator.zipkin.EmitV1HttpConventions to also be enabled."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45089"),
	featuregate.WithRegisterFromVersion("v0.154.0"),
)

var PkgTranslatorZipkinDontEmitV0NetworkConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.DontEmitV0NetworkConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator no longer emits the deprecated net.host.ip, net.peer.ip, and peer.service (semconv v1.12.0) attributes. Requires pkg.translator.zipkin.EmitV1NetworkConventions to also be enabled."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45041"),
	featuregate.WithRegisterFromVersion("v0.147.0"),
)

var PkgTranslatorZipkinDontEmitV0ScopeConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.DontEmitV0ScopeConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator no longer emits the deprecated otel.library.name and otel.library.version attributes (semconv v1.25.0). Requires pkg.translator.zipkin.EmitV1ScopeConventions to also be enabled."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45089"),
	featuregate.WithRegisterFromVersion("v0.154.0"),
)

var PkgTranslatorZipkinEmitV1CloudResourceConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.EmitV1CloudResourceConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator emits cloud.resource_id (semconv v1.40.0) instead of the deprecated faas.id (semconv v1.18.0)."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45080"),
	featuregate.WithRegisterFromVersion("v0.155.0"),
)

var PkgTranslatorZipkinEmitV1HTTPConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.EmitV1HttpConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator emits http.response.status_code (semconv v1.40.0) instead of the deprecated http.status_code (semconv v1.25.0)."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45089"),
	featuregate.WithRegisterFromVersion("v0.154.0"),
)

var PkgTranslatorZipkinEmitV1NetworkConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.EmitV1NetworkConventions",
	featuregate.StageBeta,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator emits network.local.address and network.peer.address and service.peer.name (semconv v1.40.0) instead of the deprecated net.host.ip, net.peer.ip, and peer.service (semconv v1.12.0)."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45041"),
	featuregate.WithRegisterFromVersion("v0.147.0"),
)

var PkgTranslatorZipkinEmitV1ScopeConventionsFeatureGate = featuregate.GlobalRegistry().MustRegister(
	"pkg.translator.zipkin.EmitV1ScopeConventions",
	featuregate.StageAlpha,
	featuregate.WithRegisterDescription("When enabled, the Zipkin translator emits otel.scope.name and otel.scope.version (semconv v1.40.0) instead of the deprecated otel.library.name and otel.library.version (semconv v1.25.0)."),
	featuregate.WithRegisterReferenceURL("https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45089"),
	featuregate.WithRegisterFromVersion("v0.154.0"),
)
