// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestResourceBuilder(t *testing.T) {
	for _, tt := range []string{"default", "all_set", "none_set"} {
		t.Run(tt, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt)
			rb := NewResourceBuilder(cfg)
			rb.SetHostName("host.name-val")
			rb.SetOracledbDatabaseSid("oracledb.database.sid-val")
			rb.SetOracledbInstanceName("oracledb.instance.name-val")
			rb.SetOracledbLogFileName("oracledb.log.file.name-val")
			rb.SetOracledbLogFilePath("oracledb.log.file.path-val")
			rb.SetOracledbLogSource("oracledb.log.source-val")

			res := rb.Emit()
			assert.Equal(t, 0, rb.Emit().Attributes().Len()) // Second call should return empty Resource

			switch tt {
			case "default":
				assert.Equal(t, 6, res.Attributes().Len())
			case "all_set":
				assert.Equal(t, 6, res.Attributes().Len())
			case "none_set":
				assert.Equal(t, 0, res.Attributes().Len())
				return
			default:
				assert.Failf(t, "unexpected test case: %s", tt)
			}

			val, ok := res.Attributes().Get("host.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "host.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("oracledb.database.sid")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "oracledb.database.sid-val", val.Str())
			}
			val, ok = res.Attributes().Get("oracledb.instance.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "oracledb.instance.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("oracledb.log.file.name")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "oracledb.log.file.name-val", val.Str())
			}
			val, ok = res.Attributes().Get("oracledb.log.file.path")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "oracledb.log.file.path-val", val.Str())
			}
			val, ok = res.Attributes().Get("oracledb.log.source")
			assert.True(t, ok)
			if ok {
				assert.Equal(t, "oracledb.log.source-val", val.Str())
			}
		})
	}
}
