{
 "title": "Lock Insights",
 "tags": [ "lock-insights" ],
 "time": { "from": "2022-01-06T07:38:05.715Z", "to": "2022-01-06T07:39:37.570Z" },
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "lock_topn",
    "label": "Top 10 locks",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_lock_stats_top_lock_wait_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total (all locks)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total lock wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (database) (database_spanner_lock_stats_total_total_lock_wait_seconds{database=~\"${database}\",instance_id=~\"${instance}\",project_id=~\"${project}\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Top Locks (per lock)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Lock wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (row_range_start_key) (database_spanner_lock_stats_top_lock_wait_seconds{database=~\"${database}\",instance_id=~\"${instance}\",project_id=~\"${project}\", row_range_start_key=~\"${lock_topn}\"})",
     "legendFormat": "{{row_range_start_key}}"
    }
   ]
  },
  {
   "title": "Top Locks",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_lock_stats_top_lock_wait_seconds{database=~\"${database}\",instance_id=~\"${instance}\",project_id=~\"${project}\", row_range_start_key=~\"${lock_topn}\"}",
     "legendFormat": "{{row_range_start_key}}"
    }
   ]
  }
 ]
}