{
 "title": "Monitoring dashboard",
 "description": "Cloud Monitoring | Instance dashboard",
 "tags": [ "cloud-monitoring-instance" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "gcmds", "label": "Cloud Monitoring", "query": "stackdriver" },
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   },
   {
    "name": "latencyPercentile",
    "label": "Latency percentile",
    "query": "99th percentile : 99, 50th percentile : 50"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization - rolling avarage 24 hours",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "$instance",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/cpu/smoothed_utilization'\n| filter\n    (resource.instance_id == '$instance')\n| group_by 1m,\n    [value_smoothed_utilization_mean: mean(value.smoothed_utilization)]\n| every 1m\n| group_by [resource.instance_id],\n    [value_smoothed_utilization_mean_aggregate:\n       aggregate(value_smoothed_utilization_mean)]",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Node count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Node count",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/node_count'\n| filter\n    resource.instance_id == '$instance'\n| group_by 1m, [value_node_count_mean: mean(value.node_count)]\n| every 1m\n| group_by [], [value_node_count_mean_max: max(value_node_count_mean)]",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "CPU utilization by User & System Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.priority}} priority - System",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/cpu/utilization_by_priority'\n| filter\n    resource.instance_id == '$instance' && metric.is_system && metric.database =~ '$database'\n| group_by 1m,\n    [value_utilization_by_priority_mean: mean(value.utilization_by_priority)]\n| every 1m\n| group_by [metric.priority, metric.is_system],\n    [value_utilization_by_priority_mean_aggregate:\n       aggregate(value_utilization_by_priority_mean)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.priority}} priority - User",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/cpu/utilization_by_priority'\n| filter\n    resource.instance_id == '$instance' && !metric.is_system && (metric.database =~ '$database')\n| group_by 1m,\n    [value_utilization_by_priority_mean: mean(value.utilization_by_priority)]\n| every 1m\n| group_by [metric.priority, metric.is_system],\n    [value_utilization_by_priority_mean_aggregate:\n       aggregate(value_utilization_by_priority_mean)]\n",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Total CPU utilization (Operation Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.category}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/cpu/utilization_by_operation_type'\n| filter\n    resource.instance_id == '$instance' && metric.database =~ '$database'\n| group_by 1m,\n    [value_utilization_by_operation_type_mean:\n       mean(value.utilization_by_operation_type)]\n| every 1m\n| group_by [metric.category],\n    [value_utilization_by_operation_type_mean_aggregate:\n       aggregate(value_utilization_by_operation_type_mean)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Latency - $latencyPercentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Read",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/request_latencies'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead')\n    && (metric.database =~ '$database')\n| group_by 1m,\n    [value_request_latencies_aggregate: aggregate(value.request_latencies)]\n| every 1m\n| group_by [],\n    [value_request_latencies_aggregate_percentile:\n       percentile(value_request_latencies_aggregate, $latencyPercentile)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Write",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/request_latencies'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method == 'Commit')\n    && (metric.database =~ '$database')\n| group_by 1m,\n    [value_request_latencies_aggregate: aggregate(value.request_latencies)]\n| every 1m\n| group_by [],\n    [value_request_latencies_aggregate_percentile:\n       percentile(value_request_latencies_aggregate, $latencyPercentile)]\n",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Latency (API method) - $latencyPercentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.method}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/request_latencies'\n| filter\n    resource.instance_id == '$instance' && metric.database =~ '$database'\n| group_by 1m,\n    [value_request_latencies_aggregate: aggregate(value.request_latencies)]\n| every 1m\n| group_by [metric.method],\n    [value_request_latencies_aggregate_percentile:\n       percentile(value_request_latencies_aggregate, $latencyPercentile)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Operations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Read",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead'\n     && metric.status == 'OK') && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Read error",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead'\n     && metric.status != 'OK') && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Write",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method == 'Commit' && metric.status == 'OK') && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Write error",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method == 'Commit' && metric.status != 'OK') && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Operations per second (API Method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.method}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    resource.instance_id == '$instance' && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.method],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Read",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/sent_bytes_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead')\n     && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_sent_bytes_count_aggregate: aggregate(value.sent_bytes_count)]\n",
      "valueType": ""
     }
    },
    {
     "metricQuery": {
      "aliasBy": "Write",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/received_bytes_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method =~ 'Commit')\n    && (metric.database =~ '$database')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_received_bytes_count_aggregate: aggregate(value.received_bytes_count)]\n",
      "valueType": ""
     }
    }
   ]
  },
  {
   "title": "Throughput (API Method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.method}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/sent_bytes_count'\n| filter\n    resource.instance_id == '$instance' && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.method],\n    [value_sent_bytes_count_aggregate: aggregate(value.sent_bytes_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Total backups storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Total backups storage",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/backup/used_bytes'\n| filter\n    resource.instance_id == '$instance' && (metric.database =~ '$database')\n| group_by 1m, [value_used_bytes_mean: mean(value.used_bytes)]\n| every 1m\n| group_by [],\n    [value_used_bytes_mean_aggregate: aggregate(value_used_bytes_mean)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Total database storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Total database storage",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/storage/used_bytes'\n| filter\n    resource.instance_id == '$instance' && (metric.database =~ '$database')\n| group_by 1m, [value_used_bytes_mean: mean(value.used_bytes)]\n| every 1m\n| group_by [],\n    [value_used_bytes_mean_aggregate: aggregate(value_used_bytes_mean)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  }
 ]
}