{
 "title": "Transaction details",
 "tags": [ "transaction-details" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "txn_topn",
    "label": "Top 10 transactions",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_txn_stats_top_avg_total_latency_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average total latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_avg_total_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Average commit latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_avg_commit_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Average bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Average participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_avg_participants{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Commit attempt count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_commit_attempt_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Commit abort count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_commit_abort_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Commit retry count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_commit_retry_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Commit failed precondition count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_commit_failed_precondition_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
     "legendFormat": "{{fingerprint}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "database_spanner_txn_stats_top_avg_total_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_commit_attempt_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_avg_commit_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_commit_abort_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_commit_retry_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_commit_failed_precondition_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_avg_participants{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    },
    {
     "expr": "database_spanner_txn_stats_top_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
    }
   ]
  }
 ]
}