{
 "title": "Transaction Insights",
 "tags": [ "transaction-insights" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "txn_topn",
    "label": "Top 10 transactions",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_txn_stats_top_avg_total_latency_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total (all transactions)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average total latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_avg_total_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average commit latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_avg_commit_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Average participants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_avg_participants{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Commit attempt count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_commit_attempt_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Commit abort count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_commit_abort_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Commit retry count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_commit_retry_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Commit failed  precondition count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_total_commit_failed_precondition_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\"}",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Transactions (per transaction)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average total latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_avg_total_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Average commit latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_avg_commit_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Average bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Average participants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_avg_participants{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Commit attempt count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_commit_attempt_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Commit abort count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_commit_abort_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Commit retry count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_commit_retry_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Commit failed precondition count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_commit_failed_precondition_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}",
       "legendFormat": "{{fingerprint}}"
      }
     ]
    },
    {
     "title": "Top Transactions",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "database_spanner_txn_stats_top_avg_total_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_commit_attempt_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_avg_commit_latency_seconds{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_commit_abort_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_commit_retry_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_commit_failed_precondition_count{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_avg_participants{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      },
      {
       "expr": "database_spanner_txn_stats_top_avg_bytes{project_id=~\"$project\",instance_id=~\"$instance\",database=~\"$database\",fingerprint=~\"$txn_topn\"}"
      }
     ]
    }
   ]
  }
 ]
}