FROM apache/spark:3.4.0-python3

COPY sparkprograms/long_running.py /opt/spark/examples/src/main/python/long_running.py
RUN chmod +x /opt/spark/examples/src/main/python/long_running.py

CMD [ "/opt/spark/bin/spark-submit", "/opt/spark/examples/src/main/python/long_running.py" ]

EXPOSE 4040
