display_name: Simple Prometheus Receiver
type: prometheus_simple

description: |
  This receiver provides a simple configuration interface to configure the
  prometheus receiver to scrape metrics from a single target.

status:
  class: receiver
  stability:
    beta: [metrics]
  distributions: [contrib]
  codeowners:
    active: [fatsheep9146]

tests:
  config:
  goleak:
    ignore:
      top:
        # See https://github.com/census-instrumentation/opencensus-go/issues/1191 for more information.
        - "go.opencensus.io/stats/view.(*worker).start"
