type: object
properties:
  audience:
    type: array
    items:
      type: string
  issuer:
    type: string
  key_id:
    type: string
  private_key:
    $ref: go.opentelemetry.io/collector/config/configopaque.string
  ttl:
    type: string
    format: duration
