version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest@sha256:c959cb1484133cd978079d2696b4d903ba489e794db80f0f36469cb5e93ba468
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy-config.yaml", "-l", "debug"]
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./certs/envoy.crt:/etc/envoy.crt
      - ./certs/envoy.key:/etc/envoy.key
      - ./certs/ca.crt:/etc/ca.crt
      - ./envoy-config.yaml:/etc/envoy-config.yaml
  otel-collector:
    image: otel/opentelemetry-collector:0.160.0@sha256:e495787f07dbe432ce763ebaf5bc3d113850e9eee2250ade7a3da6a882d0d69a
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./certs/otel-collector.crt:/etc/otel-collector.crt
      - ./certs/otel-collector.key:/etc/otel-collector.key
      - ./certs/ca.crt:/etc/ca.crt
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "55690"       # OTLP gRPC receiver
    depends_on:
      - envoy
