$defs:
  attribute_context_switch_type:
    description: AttributeContextSwitchType specifies the value context_switch_type attribute.
    type: integer
  attribute_direction:
    description: AttributeDirection specifies the value direction attribute.
    type: integer
  attribute_paging_fault_type:
    description: AttributePagingFaultType specifies the value paging_fault_type attribute.
    type: integer
  attribute_state:
    description: AttributeState specifies the value state attribute.
    type: integer
  metric_config:
    description: MetricConfig provides common config for a particular metric.
    type: object
    properties:
      enabled:
        type: boolean
  metrics_builder_config:
    description: MetricsBuilderConfig is a configuration for process metrics builder.
    type: object
    properties:
      metrics:
        $ref: metrics_config
      resource_attributes:
        $ref: resource_attributes_config
  metrics_config:
    description: MetricsConfig provides config for process metrics.
    type: object
    properties:
      process.context_switches:
        $ref: metric_config
      process.cpu.time:
        $ref: metric_config
      process.cpu.utilization:
        $ref: metric_config
      process.disk.io:
        $ref: metric_config
      process.disk.operations:
        $ref: metric_config
      process.handles:
        $ref: metric_config
      process.memory.usage:
        $ref: metric_config
      process.memory.utilization:
        $ref: metric_config
      process.memory.virtual:
        $ref: metric_config
      process.open_file_descriptors:
        $ref: metric_config
      process.paging.faults:
        $ref: metric_config
      process.signals_pending:
        $ref: metric_config
      process.threads:
        $ref: metric_config
      process.uptime:
        $ref: metric_config
  resource_attribute_config:
    description: ResourceAttributeConfig provides common config for a particular resource attribute.
    type: object
    properties:
      enabled:
        type: boolean
      metrics_exclude:
        description: 'Experimental: MetricsExclude defines a list of filters for attribute values. If the list is not empty, metrics with matching resource attribute values will not be emitted. MetricsInclude has higher priority than MetricsExclude.'
        type: array
        items:
          $ref: go.opentelemetry.io/collector/filter.config
      metrics_include:
        description: 'Experimental: MetricsInclude defines a list of filters for attribute values. If the list is not empty, only metrics with matching resource attribute values will be emitted.'
        type: array
        items:
          $ref: go.opentelemetry.io/collector/filter.config
  resource_attributes_config:
    description: ResourceAttributesConfig provides config for process resource attributes.
    type: object
    properties:
      process.cgroup:
        $ref: resource_attribute_config
      process.command:
        $ref: resource_attribute_config
      process.command_line:
        $ref: resource_attribute_config
      process.executable.name:
        $ref: resource_attribute_config
      process.executable.path:
        $ref: resource_attribute_config
      process.owner:
        $ref: resource_attribute_config
      process.parent_pid:
        $ref: resource_attribute_config
      process.pid:
        $ref: resource_attribute_config
