type: object
properties:
  extensions_socket:
    type: string
  queries:
    type: array
    items:
      type: string
  collections:
    type: array
    items:
      type: string
      enum: [system_info, package_info, os_info, secureboot_info, users_info]
  snapshot_interval:
    type: string
  storage:
    type: string
allOf:
  - $ref: go.opentelemetry.io/collector/scraper/scraperhelper.controller_config
