# Use the official Redis image as the base
FROM redis:8.0.1

RUN apt update && apt install --assume-yes socat

# Seems to be an upstream issue with testcontainers or scraperint when using named nodes or clusters, so manually do it
COPY cluster.sh /usr/local/bin/cluster.sh
COPY configure-nodes.sh /usr/local/bin/configure-nodes.sh
COPY redis-cluster.conf /etc/redis-cluster.conf

RUN chown redis:redis /usr/local/bin/cluster.sh
RUN chmod +x /usr/local/bin/cluster.sh

RUN chown redis:redis /usr/local/bin/configure-nodes.sh
RUN chmod +x /usr/local/bin/configure-nodes.sh

RUN configure-nodes.sh
RUN chown redis:redis /etc/redis-cluster*.conf

RUN mkdir -p /var/log/redis
RUN chgrp redis /var/log/redis

EXPOSE 6379
EXPOSE 6380
EXPOSE 6381
EXPOSE 6382
EXPOSE 6383
EXPOSE 6384
EXPOSE 6385
ENTRYPOINT ["cluster.sh"]
CMD ["cluster.sh"]
