$defs:
  source:
    type: object
    properties:
      file:
        description: File specifies a local file as the strategies source
        type: string
      reload_interval:
        description: ReloadInterval determines the periodicity to refresh the strategies
        type: string
        format: duration
      remote:
        description: Remote defines the remote location for the file
        x-pointer: true
        $ref: go.opentelemetry.io/collector/config/configgrpc.client_config
description: Config has the configuration for the extension enabling the health check extension, used to report the health status of the service.
type: object
properties:
  grpc:
    x-pointer: true
    $ref: go.opentelemetry.io/collector/config/configgrpc.server_config
  http:
    x-pointer: true
    $ref: go.opentelemetry.io/collector/config/confighttp.server_config
  source:
    description: Source configures the source for the strategies file. One of `remote` or `file` has to be specified.
    $ref: source
