ARG MONGO_VERSION=8.2@sha256:e0ce8c35124d4a9f9785532d1f268f39e9728ffa1cb38f46fa482436424c4bd3
FROM mongo:${MONGO_VERSION}

COPY scripts/setup_top_query.sh /setup_top_query.sh
RUN chmod +x /setup_top_query.sh

EXPOSE 27017
