// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms, confmap.WithErrorUnused())
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for k8s/job metrics.
type MetricsConfig struct {
	K8sJobActivePods            MetricConfig `mapstructure:"k8s.job.active_pods"`
	K8sJobDesiredSuccessfulPods MetricConfig `mapstructure:"k8s.job.desired_successful_pods"`
	K8sJobFailedPods            MetricConfig `mapstructure:"k8s.job.failed_pods"`
	K8sJobMaxParallelPods       MetricConfig `mapstructure:"k8s.job.max_parallel_pods"`
	K8sJobSuccessfulPods        MetricConfig `mapstructure:"k8s.job.successful_pods"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		K8sJobActivePods: MetricConfig{
			Enabled: true,
		},
		K8sJobDesiredSuccessfulPods: MetricConfig{
			Enabled: true,
		},
		K8sJobFailedPods: MetricConfig{
			Enabled: true,
		},
		K8sJobMaxParallelPods: MetricConfig{
			Enabled: true,
		},
		K8sJobSuccessfulPods: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

// ResourceAttributesConfig provides config for k8s/job resource attributes.
type ResourceAttributesConfig struct {
	K8sJobName             ResourceAttributeConfig `mapstructure:"k8s.job.name"`
	K8sJobUID              ResourceAttributeConfig `mapstructure:"k8s.job.uid"`
	K8sNamespaceName       ResourceAttributeConfig `mapstructure:"k8s.namespace.name"`
	OpencensusResourcetype ResourceAttributeConfig `mapstructure:"opencensus.resourcetype"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		K8sJobName: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sJobUID: ResourceAttributeConfig{
			Enabled: true,
		},
		K8sNamespaceName: ResourceAttributeConfig{
			Enabled: true,
		},
		OpencensusResourcetype: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for k8s/job metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
