FROM ubuntu:22.04 as download

RUN \
    apt-get autoremove -qq && \
    apt-get update -qq && \
    apt-get install -qq -y curl && \
    curl -L -o /riak.deb https://files.tiot.jp/riak/kv/3.0/3.0.9/ubuntu/focal64/riak_3.0.9-OTP20.3_amd64.deb

FROM ubuntu:20.04

COPY --from=download /riak.deb /riak.deb

RUN \
    apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qq -y -f /riak.deb

WORKDIR /var/lib/riak

EXPOSE 8087
EXPOSE 8098

ENV RIAK_VERSION 3.0.2
ENV RIAK_HOME /usr/lib/riak
ENV RIAK_FLAVOR KV

COPY riak.conf /etc/riak/riak.conf
COPY entrypoint.sh /usr/lib/riak/entrypoint.sh
RUN chmod +x /usr/lib/riak/entrypoint.sh

ENTRYPOINT [ "/usr/lib/riak/entrypoint.sh" ]
