// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/aerospike component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("aerospike")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/aerospikereceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
