change_type: bug_fix

component: receiver/prometheus_remote_write

note: Fix exemplars for counters with multiple label-set variants being attached to the wrong datapoint.

issues: [48674]

subtext:

change_logs: [user]
