$defs:
  critical_path_config:
    description: CriticalPathConfig holds configuration for critical path processing.
    type: object
    properties:
      enabled:
        type: boolean
  transactions_config:
    description: TransactionsConfig holds configuration for transactions.
    type: object
    properties:
      enabled:
        type: boolean
type: object
allOf:
  - $ref: transactions_config
  - $ref: critical_path_config
