{
 "title": "SPM Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(calls_total, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total # of spans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Spans per service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Avg Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(calls_total{service_name=~\"$service\",status_code=~\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Error Rate per Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name) (rate(calls_total{service_name=~\"$service\",status_code=~\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum by (service_name) (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Latency per Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{service_name=~\"$service\"}[$__rate_interval])) by (service_name,le))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (service_name)(rate(calls_total[$__rate_interval]))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket[5m])) by (service_name,le))"
    },
    {
     "expr": "sum by (service_name)(rate(calls_total{status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))/sum by (service_name)(rate(calls_total[$__rate_interval]))"
    }
   ]
  },
  { "title": "$service - Stats per Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "service" },
  {
   "title": "Total # of spans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Latency per Operation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_bucket{service_name=~\"$service\"}[$__rate_interval])) by (operation,le))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Spans per service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Error Rate per Operation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(calls_total{service_name=~\"$service\",status_code=~\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum by (operation) (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg Error Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(calls_total{service_name=~\"$service\",status_code=~\"STATUS_CODE_ERROR\"}[$__rate_interval])) / sum (rate(calls_total{service_name=~\"$service\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}