# This action adds the "next release" milestone to a pull request
# when it is merged. The "next release" milestone is managed
# by the "Project: Rotate Milestone" action.

name: 'Project: Add PR to Milestone'
on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: read

jobs:
  update-pr:
    permissions:
      pull-requests: write # required for adding milestone to PRs
    if: github.event.pull_request.merged && github.repository_owner == 'open-telemetry'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            })
            for (const milestone of milestones.data) {
              if (milestone.title == "next release") {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  milestone: milestone.number
                });
                return
              }
            }
