# A rockylinux8.5 image with systemd enabled.  Must be run with:
# `-d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro` flags
FROM rockylinux:9.3

ENV container docker

RUN dnf install -y initscripts

CMD ["/usr/sbin/init"]
